language: python
install:
- pip install pytest
- pip install geojson
- pip install forked-path
- npm install -g geojson-merge
before_script:
- echo "about to deploy..."
  - geojson-merge *.topojson > newmap.topojson
  - rm class-pins.topojson
  - mv newmap.topojson class-pins.topojson
script: py.test
deploy:
  on:
    repo: brianamarie/travel-log
before_install:
- openssl aes-256-cbc -K $encrypted_4f8e0108f7a1_key -iv $encrypted_4f8e0108f7a1_iv
  -in deploy-key.enc -out deploy-key -d
